version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - chore

  - package-ecosystem: npm
    directory: '/projects/ng-pdf-viewer'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - chore
